#!/sbin/busybox sh

if [[ ! -z $2 ]]; then
    filename=$(basename $2)
fi

if [[ ! -z $3 ]]; then
  evalcmd='eval "$filename=$3"'
  eval $evalcmd
fi

mdnie_predef="0"
mdnie_find=`grep "mdnie_predef" $DEFAULT_PROFILE | cut -d'=' -f2`

write_value() {  
  echo "$1=$2" >> $DEFAULT_PROFILE
}

edit_value() {
  g_find=`grep $1=.* $DEFAULT_PROFILE`
    
  if [[ -z $g_find ]]; then
    write_value $1 $2
  else
    sed -i "s/$1=[^ ]*/$1=$2/" $DEFAULT_PROFILE 
  fi
}

write_values(){
  edit_value mdnie_black $mdnie_black
  edit_value mdnie_blue_red $mdnie_blue_red
  edit_value mdnie_blue_green $mdnie_blue_green
  edit_value mdnie_blue_blue $mdnie_blue_blue
  edit_value mdnie_cyan_red $mdnie_cyan_red
  edit_value mdnie_cyan_green $mdnie_cyan_green
  edit_value mdnie_cyan_blue $mdnie_cyan_blue
  edit_value mdnie_green_red $mdnie_green_red
  edit_value mdnie_green_green $mdnie_green_green
  edit_value mdnie_green_blue $mdnie_green_blue
  edit_value mdnie_magenta_red $mdnie_magenta_red
  edit_value mdnie_magenta_green $mdnie_magenta_green
  edit_value mdnie_magenta_blue $mdnie_magenta_blue
  edit_value mdnie_red_red $mdnie_red_red
  edit_value mdnie_red_green $mdnie_red_green
  edit_value mdnie_red_blue $mdnie_red_blue
  edit_value mdnie_white_red $mdnie_white_red
  edit_value mdnie_white_green $mdnie_white_green
  edit_value mdnie_white_blue $mdnie_white_blue
  edit_value mdnie_yellow_red $mdnie_yellow_red
  edit_value mdnie_yellow_green $mdnie_yellow_green
  edit_value mdnie_yellow_blue $mdnie_yellow_blue
  edit_value mdnie_predef $mdnie_predef 

# Black
  echo $mdnie_black > /sys/class/mdnie/mdnie/black
# Blue
  echo $mdnie_blue_red > /sys/class/mdnie/mdnie/blue_red
  echo $mdnie_blue_green > /sys/class/mdnie/mdnie/blue_green
  echo $mdnie_blue_blue > /sys/class/mdnie/mdnie/blue_blue
# Cyan
  echo $mdnie_cyan_red > /sys/class/mdnie/mdnie/cyan_red
  echo $mdnie_cyan_green > /sys/class/mdnie/mdnie/cyan_green
  echo $mdnie_cyan_blue > /sys/class/mdnie/mdnie/cyan_blue
# Green
  echo $mdnie_green_red > /sys/class/mdnie/mdnie/green_red
  echo $mdnie_green_green > /sys/class/mdnie/mdnie/green_green
  echo $mdnie_green_blue > /sys/class/mdnie/mdnie/green_blue
# Magenta
  echo $mdnie_magenta_red > /sys/class/mdnie/mdnie/magenta_red
  echo $mdnie_magenta_green > /sys/class/mdnie/mdnie/magenta_green
  echo $mdnie_magenta_blue > /sys/class/mdnie/mdnie/magenta_blue
# Red
  echo $mdnie_red_red > /sys/class/mdnie/mdnie/red_red
  echo $mdnie_red_green > /sys/class/mdnie/mdnie/red_green
  echo $mdnie_red_blue > /sys/class/mdnie/mdnie/red_blue
# White
  echo $mdnie_white_red > /sys/class/mdnie/mdnie/white_red
  echo $mdnie_white_green > /sys/class/mdnie/mdnie/white_green
  echo $mdnie_white_blue > /sys/class/mdnie/mdnie/white_blue
# Yellow
  echo $mdnie_yellow_red > /sys/class/mdnie/mdnie/yellow_red
  echo $mdnie_yellow_green > /sys/class/mdnie/mdnie/yellow_green
  echo $mdnie_yellow_blue > /sys/class/mdnie/mdnie/yellow_blue

}

case "$mdniepredef" in
  0)
    #Natural
    mdnie_black="0"
    mdnie_blue_red="28"
    mdnie_blue_green="12"
    mdnie_blue_blue="232"
    mdnie_cyan_red="29"
    mdnie_cyan_green="241"
    mdnie_cyan_blue="222"
    mdnie_green_red="20"
    mdnie_green_green="231"
    mdnie_green_blue="0"
    mdnie_magenta_red="251"
    mdnie_magenta_green="23"
    mdnie_magenta_blue="231"
    mdnie_red_red="240"
    mdnie_red_green="19"
    mdnie_red_blue="15"
    mdnie_white_red="255"
    mdnie_white_green="248"
    mdnie_white_blue="241"
    mdnie_yellow_red="240"
    mdnie_yellow_green="242"
    mdnie_yellow_blue="39"
    mdnie_predef="0"
    write_values
    ;;
  1)
    #Standard
    mdnie_black="0"
    mdnie_blue_red="0"
    mdnie_blue_green="0"
    mdnie_blue_blue="255"
    mdnie_cyan_red="0"
    mdnie_cyan_green="255"
    mdnie_cyan_blue="255"
    mdnie_green_red="0"
    mdnie_green_green="255"
    mdnie_green_blue="0"
    mdnie_magenta_red="255"
    mdnie_magenta_green="0"
    mdnie_magenta_blue="255"
    mdnie_red_red="255"
    mdnie_red_green="0"
    mdnie_red_blue="0"
    mdnie_white_red="255"
    mdnie_white_green="255"
    mdnie_white_blue="255"
    mdnie_yellow_red="255"
    mdnie_yellow_green="255"
    mdnie_yellow_blue="0"
    mdnie_predef="1"
    write_values
    ;;
  *)
    if [[ ! -z $mdnie_find ]]; then
      mdnie_predef="$mdnie_find"
    fi 
    ;;
esac;

eval echo $mdnie_predef
